version: "3"
services:
  wik-wak-mongo-1:
    hostname: local-wik-wak-mongo-1
    container_name: local-wik-wak-mongo-1
    image: mongo:4.0-xenial
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    expose:
      - 27017
    ports:
      - 27011:27017
    restart:
      always
    environment:
      - MONGO_INITDB_DATABASE=wik_wak_development
      - MONGO_INITDB_DATABASE=wiki_wak_test
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  wik-wak-mongo-2:
    hostname: local-wik-wak-mongo-2
    container_name: local-wik-wak-mongo-2
    image: mongo:4.0-xenial
    expose:
    - 27017
    ports:
    - 27012:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  wik-wak-mongo-3:
    hostname: local-wik-wak-mongo-3
    container_name: local-wik-wak-mongo-3
    image: mongo:4.0-xenial
    expose:
    - 27017
    ports:
    - 27013:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  redis:
    container_name: 'wik-wak-redis'
    image: "redis:alpine"
    ports:
      - "6379:6379"
