version: "3"
services:
  database: 
    container_name: 'wik-wak-mongo'
    image: mongo
    environment: 
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /mongo-volume:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=wik_wak_development
      - MONGO_INITDB_DATABASE=wiki_wak_test
  redis:
    container_name: 'wik-wak-redis'
    image: "redis:alpine"
    ports:
      - "6379:6379"
